version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: stylelint-config-standard
        versions:
          - 22.0.0
      - dependency-name: core-js
        versions:
          - 3.10.2
      - dependency-name: "@types/helmet"
        versions:
          - 4.0.0
      - dependency-name: "@types/react-dom"
        versions:
          - 17.0.0
          - 17.0.1
          - 17.0.2
          - 17.0.3
      - dependency-name: eslint-config-prettier
        versions:
          - 7.2.0
          - 8.0.0
          - 8.1.0
          - 8.2.0
      - dependency-name: "@types/react"
        versions:
          - 17.0.0
          - 17.0.1
          - 17.0.2
          - 17.0.3
      - dependency-name: "@types/react-test-renderer"
        versions:
          - 17.0.0
          - 17.0.1
      - dependency-name: "@types/serialize-javascript"
        versions:
          - 5.0.0
      - dependency-name: webpack-bundle-analyzer
        versions:
          - 4.4.0
          - 4.4.1
      - dependency-name: fork-ts-checker-webpack-plugin
        versions:
          - 6.1.0
          - 6.1.1
          - 6.2.0
          - 6.2.1
      - dependency-name: mini-css-extract-plugin
        versions:
          - 1.3.5
          - 1.3.6
          - 1.3.7
          - 1.3.8
          - 1.3.9
          - 1.4.0
          - 1.4.1
      - dependency-name: webpack-dev-middleware
        versions:
          - 4.1.0
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    open-pull-requests-limit: 10
